services:
  android-emulator:
    build:
      context: .
      args:
        - API_LEVEL=34
        - CMD_LINE_VERSION=11076708_latest
        - IMG_TYPE=google_apis
    ports:
      - 5554:5554
      - 5555:5555
    environment:
      - DISABLE_ANIMATION=true
      - DISABLE_HIDDEN_POLICY=true
      - SKIP_AUTH=false
      #- ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - MEMORY=8192
      - CORES=8
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./keys/adbkey:/root/.android/adbkey:ro
      - ./keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./android_avd:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"